Update to upstream version
nucypher/stake-nucypher pull request #1
Opened 2020-08-30 09:56 UTC by cryptoseal86

2020-08-30 21:14 UTC, cryptoseal86 commented
Checked with mainnet contracts and updated addresses/fixed some issues with renaming of contract events

2020-08-31 21:31 UTC, cygnusv requested changes

2020-08-31 21:31 UTC, cygnusv commented on src/config.json
> +    "stakingEscrowAddress": "0x33d28fcb3204b146ea8d5f059ebef8679f992deb",
```suggestion
    "stakingEscrowAddress": "0xbbD3C0C794F40c4f993B03F65343aCC6fcfCb2e2",
```

2020-08-31 21:31 UTC, cygnusv commented on src/config.json
> +    "policyManagerAddress": "0xF1Fe01eb9dfDb1F43BEd97923E96176526525EF4",
```suggestion
    "policyManagerAddress": "0x67E4A942c067Ff25cE7705B69C318cA2Dfa54D64",
```

2020-08-31 21:31 UTC, cygnusv commented on src/config.json
> +    "workLockAddress": "0xe9778e69a961e64d3cdbb34cf6778281d34667c2"
```suggestion
    "workLockAddress": "0xe9778E69a961e64d3cdBB34CF6778281d34667c2"
```

2020-08-31 21:31 UTC, cygnusv commented on src/config.json
> +    "stakingEscrowAddress": "0x33d28fcb3204b146ea8d5f059ebef8679f992deb",
This needs to be the address of the proxy.

2020-08-31 21:32 UTC, cygnusv commented on src/config.json
> +    "policyManagerAddress": "0xF1Fe01eb9dfDb1F43BEd97923E96176526525EF4",
Same.

2020-08-31 21:32 UTC, cygnusv commented on src/config.json
> +    "workLockAddress": "0xe9778e69a961e64d3cdbb34cf6778281d34667c2"
Checksum validation.

2020-09-06 02:36 UTC, vepkenez approved these changes

2020-09-07 01:21 UTC, KPrasch commented on src/config.json
> +  },
:+1: Looks correct.

2020-09-07 01:21 UTC, KPrasch approved these changes

2020-09-07 01:22 UTC, merged